service: laravel

bref:
  team: laravel-aws

provider:
  name: aws
  region: us-east-1
  environment:
    APP_ENV: production
    SESSION_DRIVER: cookie
    QUEUE_CONNECTION: sqs
    FILESYSTEM_DISK: s3
    S3_BUCKET: ${cf:laravel.S3Bucket} # reference the created S3 bucket
    DB_CONNECTION: mysql
    DB_HOST: ${cf:laravel.RDSInstanceEndpoint}
    DB_PORT: 3306
    DB_DATABASE: laravel
    DB_USERNAME: laravel
    DB_PASSWORD: laravelpass
    AWS_DEFAULT_REGION: us-east-1

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!resources/css/**'
    - '!resources/images/**'
    - '!resources/js/**'
    - '!storage/**'
    - '!tests/**'
    - '!database/*.sqlite'
    - '!public/build/**'
    - 'public/build/manifest.json'

functions:
  web:
    handler: public/index.php
    runtime: php-82-fpm
    timeout: 28
    events:
      - httpApi: '*'

  artisan:
    handler: artisan
    runtime: php-82-console
    timeout: 720
    # Optional: run Laravel schedule every minute
    # events:
    #   - schedule:
    #       rate: rate(1 minute)
    #       input: '"schedule:run"'

resources:
  Resources:

    # 📁 S3 Bucket for file storage
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub '${AWS::StackName}-storage'
        AccessControl: PublicRead #makes all uploaded objects publicly readable
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    # 🐘 RDS Instance (MySQL)
    RDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: !Sub '${AWS::StackName}-db'
        Engine: mysql
        EngineVersion: 8.0.35
        DBInstanceClass: db.t3.micro   #Free Tier eligible
        AllocatedStorage: 20           #Up to 20GB free
        StorageType: gp2               #Default general purpose SSD
        MasterUsername: laravel
        MasterUserPassword: laravelpass
        BackupRetentionPeriod: 0
        PubliclyAccessible: true
        DeletionProtection: false
        MultiAZ: false                 #Disable high availability (free tier doesn’t support)
        AutoMinorVersionUpgrade: true

    # 📬 SQS Queue for Laravel jobs
    LaravelQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: laravel-queue

  Outputs:
    RDSInstanceEndpoint:
      Value: !GetAtt RDSInstance.Endpoint.Address
    S3Bucket:
      Value: !Ref S3Bucket
    LaravelQueueUrl:
      Value: !Ref LaravelQueue
