name: Deploy Laravel (Serverless + CI/CD)

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Install Laravel & Prepare for Deploy
        working-directory: ./app
        run: |
          cp .env.production .env
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy Laravel to AWS Lambda
        working-directory: ./app
        run: serverless deploy --stage production

      - name: Run Migrations If Changed (After Deploy)
        working-directory: ./app
        run: |
          echo "Checking for changed migrations..."
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^app/database/migrations/' > /dev/null; then
            echo "Migrations changed, running php artisan migrate via Lambda"
            serverless invoke -f artisan -d '{"command": "migrate --force"}'
          else
            echo "No migration changes, skipping migration"
          fi
